
name: CI - Build Backend

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      env:
        POSTGRES_USER: amigoscode
        POSTGRES_PASSWORD: password
        POSTGRES_DB: customer
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify